version: "3"
services:
  frontend:
    image: nexo-frontend
    ports:
      - "8080:8080"

  backend:
    image: nexo-backend
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/nexo?serverTimezone=UTC
    networks:
      - red-nexo
    depends_on:
      - mysqldb

  mysqldb:
    image: nexo-bbdd
    networks:
      - red-nexo
    environment:
      MYSQL_DATABASE: nexo
      MYSQL_ROOT_PASSWORD: "1234"

networks:
  red-nexo:
