version: "3"
services:
  mysqldb:
    image: nexo-bbdd
    networks:
      - red-nexo
    environment:
      MYSQL_DATABASE: nexo
      MYSQL_ROOT_PASSWORD: "1234"
  
  backend:
    image: nexo-backend
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/nexo?serverTimezone=UTC
    networks:
      - red-nexo
    # Espera a que este lista la BBDD
    depends_on:
      - mysqldb
    command: sh -c "until nc -z mysqldb 3306; do sleep 1; done; java -jar com.nexo-0.0.1.jar"

  frontend:
    image: nexo-frontend
    ports:
      - "8080:8080"

networks:
  red-nexo:
